# Generated by Django 5.2.6 on 2025-10-18 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_salescope', '0007_htmlfiles_scrappingdataalltime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HTMLFiles',
        ),
        migrations.RemoveField(
            model_name='productosuper',
            name='prod_sku',
        ),
        migrations.RemoveField(
            model_name='productosuper',
            name='scrp_id',
        ),
        migrations.RemoveField(
            model_name='productosuper',
            name='super_id',
        ),
        migrations.DeleteModel(
            name='ScrappingDataAllTime',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='super',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='ScrappingData',
        ),
        migrations.DeleteModel(
            name='ProductoSuper',
        ),
        migrations.DeleteModel(
            name='Super',
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
