# Generated by Django 5.2.6 on 2025-10-22 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_salescope', '0009_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoprecio',
            name='ean',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_salescope.productos'),
        ),
        migrations.AlterField(
            model_name='productoprecio',
            name='fuente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_salescope.fuente'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='ean',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_salescope.productos'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fuente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_salescope.fuente'),
        ),
    ]
