# Generated by Django 5.2.6 on 2025-10-22 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_salescope', '0011_productoprecio_descuento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoprecio',
            name='descuento',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='productoprecio',
            name='precio_descontado',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
