# Generated by Django 5.2.6 on 2025-11-05 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_salescope', '0015_productoprecio_precio_descontado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoprecio',
            name='fuente',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='fuente',
        ),
        migrations.RemoveField(
            model_name='productoprecio',
            name='ean',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='ean',
        ),
        migrations.DeleteModel(
            name='Fuente',
        ),
        migrations.DeleteModel(
            name='ProductoPrecio',
        ),
        migrations.DeleteModel(
            name='Productos',
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
