# Generated by Django 5.2.6 on 2025-11-05 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_salescope', '0016_remove_productoprecio_fuente_remove_venta_fuente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fuente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('super', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('EAN', models.BigIntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('marca', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoPrecio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('promocione_existente', models.BooleanField(default=False)),
                ('precio_descontado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('promocion', models.CharField(blank=True, max_length=100, null=True)),
                ('fuente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_salescope.fuente')),
                ('ean', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_salescope.productos')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateField()),
                ('fuente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_salescope.fuente')),
            ],
        ),
    ]
