# Generated by Django 5.2.6 on 2025-11-05 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_salescope', '0017_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productoprecio',
            old_name='ean',
            new_name='producto',
        ),
        migrations.RenameField(
            model_name='productoprecio',
            old_name='promocione_existente',
            new_name='promocion_existente',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='EAN',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='productos',
            name='fuente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_salescope.fuente'),
        ),
        migrations.AddField(
            model_name='productos',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='productos',
            name='name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productos',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productos',
            name='precio_descontado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productos',
            name='promocion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productos',
            name='promocion_existente',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='venta',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_salescope.productos'),
        ),
    ]
