# Generated by Django 5.2.6 on 2025-11-08 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_salescope', '0019_remove_productoprecio_producto_productoprecio_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoprecio',
            name='marca',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
