# Generated by Django 5.2.6 on 2025-11-08 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_salescope', '0020_productoprecio_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
