# Generated by Django 5.2.6 on 2025-09-17 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_salescope', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
