# Generated by Django 5.2.6 on 2025-09-19 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_salescope', '0002_delete_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('ean', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Código EAN')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScrappingData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ean', models.CharField(max_length=13)),
                ('precio', models.FloatField()),
                ('promocion', models.JSONField()),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductoSuperScraping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_sku', models.ForeignKey(db_column='prod_sku', on_delete=django.db.models.deletion.CASCADE, to='app_salescope.producto')),
                ('super_id', models.ForeignKey(db_column='super_id', on_delete=django.db.models.deletion.CASCADE, to='app_salescope.super')),
                ('scrp_id', models.ForeignKey(db_column='scrp_id', on_delete=django.db.models.deletion.CASCADE, to='app_salescope.scrappingdata')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('ean', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha', models.DateField()),
                ('super', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_salescope.super')),
            ],
        ),
    ]
