# Generated by Django 5.2.6 on 2025-09-19 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_salescope', '0003_producto_scrappingdata_productosuperscraping_venta'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductoSuperScraping',
            new_name='ProductoSuper',
        ),
    ]
