# Generated by Django 5.2.6 on 2025-10-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_salescope', '0004_rename_productosuperscraping_productosuper'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrappingdata',
            old_name='ean',
            new_name='SKU',
        ),
        migrations.AddField(
            model_name='scrappingdata',
            name='PWD',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='scrappingdata',
            name='promocion',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
