# Generated by Django 5.2.6 on 2025-10-03 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_salescope', '0005_rename_ean_scrappingdata_sku_scrappingdata_pwd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrappingdata',
            name='marca',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='scrappingdata',
            name='producto_nombre',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='scrappingdata',
            name='supermercado',
            field=models.CharField(default='', max_length=50),
        ),
    ]
