# Generated by Django 5.2.6 on 2025-10-17 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_salescope', '0006_scrappingdata_marca_scrappingdata_producto_nombre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HTMLFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ScrappingDataAllTime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('SKU', models.CharField(max_length=13)),
                ('precio', models.FloatField()),
                ('promocion', models.CharField(blank=True, max_length=32)),
                ('PWD', models.FloatField(default=0)),
                ('fecha', models.DateField()),
                ('supermercado', models.CharField(default='', max_length=50)),
                ('marca', models.CharField(default='', max_length=50)),
                ('producto_nombre', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
