# Generated by Django 5.2.6 on 2025-10-18 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_salescope', '0008_delete_htmlfiles_remove_productosuper_prod_sku_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fuente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('super', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('EAN', models.BigIntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('marca', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoPrecio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('fuente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_salescope.fuente')),
                ('ean', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_salescope.productos')),
            ],
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ean', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_salescope.productos')),
                ('fuente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_salescope.fuente')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateField()),
                ('ean', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_salescope.productos')),
                ('fuente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_salescope.fuente')),
            ],
        ),
    ]
