# Generated by Django 5.2.6 on 2025-10-22 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_salescope', '0010_alter_productoprecio_ean_alter_productoprecio_fuente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoprecio',
            name='descuento',
            field=models.TextField(blank=True, default='0', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='productoprecio',
            name='precio_descontado',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=10,
                null=True,
            ),
        ),
    ]
