# Generated by Django 5.2.6 on 2025-10-22 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_salescope', '0013_alter_productoprecio_descuento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoprecio',
            name='descuento',
        ),
        migrations.RemoveField(
            model_name='productoprecio',
            name='precio_descontado',
        ),
    ]
