# Generated by Django 5.2.6 on 2025-11-05 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_salescope', '0014_remove_productoprecio_descuento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoprecio',
            name='precio_descontado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productoprecio',
            name='promocion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productoprecio',
            name='promocione_existente',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Promocion',
        ),
    ]
