# Generated by Django 5.2.6 on 2025-11-05 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_salescope', '0018_rename_ean_productoprecio_producto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoprecio',
            name='producto',
        ),
        migrations.AddField(
            model_name='productoprecio',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
